BanhCuonPhuongAnh.laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::group(['domain'=>'cms.banhcuonphuonganh.com'],function(){

	Route::prefix('product')->group(function(){
		Route::resource('/category','ProductCategoryController');
		Route::resource('/gallery','ProductPhotoController');
		Route::resource('/hot','HotProductController');
		Route::resource('/selective','SelectiveProductController');
	});
	 
	Route::resource('/product','ProductController');
	Route::resource('/','ProductController');
	
	Route::resource('/tag','KeyWordController');

	Route::prefix('post')->group(function(){
		// Route::resource('/category','PostCategoryController');
		Route::get('/category/create', 'PostCategoryController@create')->name('postcategory.create');
		Route::get('/category', 'PostCategoryController@index')->name('postcategory.index');
		Route::post('/category', 'PostCategoryController@store')->name('postcategory.store');
		Route::delete('/category/{category}', 'PostCategoryController@destroy')->name('postcategory.destroy');
		Route::get('/category/{category}/edit', 'PostCategoryController@edit')->name('postcategory.edit');
		Route::patch('/category/{category}', 'PostCategoryController@update')->name('postcategory.update');
		Route::get('/category/{category}', 'PostCategoryController@show')->name('postcategory.show');
	});
	 
	Route::resource('/post','PostController');

	Route::prefix('news')->group(function(){
		Route::get('/category/create', 'NewsCategoryController@create')->name('newscategory.create');
		Route::get('/category', 'NewsCategoryController@index')->name('newscategory.index');
		Route::post('/category', 'NewsCategoryController@store')->name('newscategory.store');
		Route::delete('/category/{category}', 'NewsCategoryController@destroy')->name('newscategory.destroy');
		Route::get('/category/{category}/edit', 'NewsCategoryController@edit')->name('newscategory.edit');
		Route::patch('/category/{category}', 'NewsCategoryController@update')->name('newscategory.update');
		Route::get('/category/{category}', 'NewsCategoryController@show')->name('newscategory.show');
		Route::get('/category/image-crop-upload', 'NewsCategoryController@cropUploadImage');
	});
	 
	Route::resource('/news','NewsController');
	Route::resource('/config','ConfigurationController');
	Route::resource('/user','UserController');

	Route::prefix('menu')->group(function(){
		Route::get('/order','MenuController@order')->name('menu.order');
		Route::post('/orderStore','MenuController@orderStore')->name('menuorder.store');
	});
	Route::resource('/menu','MenuController');

	Route::resource('/slide','SlideController');


	Auth::routes();
	Route::get('/user/verify/{confirmation_code}','Auth\RegisterController@verifyUser')->name('activate.user');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::delete('/deleteRecord/{id}','ProductPhotoController@deleteRecord');
});

Route::group(['domain'=>'banhcuonphuonganh.com'],function(){
	Route::get('/','Client\HomeController@index');
	Route::get('/bai-viet/{slug}','Client\PostController@getDetailPost');

	//Route::get('/tin-tuc/{slug1}/{slug2}','Client\NewsController@getDetailNews');
	Route::get('{slug},{news_id}','Client\NewsController@getDetailNews')->where(['news_id' => '.{4}']);
	Route::get('/tin-tuc/{slug}','Client\NewsController@getNewsSameCategory');
	Route::get('/tin-tuc','Client\NewsController@getListNews');

	Route::get('{slug},{product_id}','Client\ProductController@getDetailProduct')->where(['product_id' => '.{6}']);
	Route::get('/san-pham/{slug}','Client\ProductController@getProductSameCategory');
	Route::get('/tag/{slug}','Client\ProductController@getProductSameTag');
	Route::get('/san-pham','Client\ProductController@getListProduct');
	Route::get('/tim-kiem','Client\ProductController@search');
	// Route::get('/slide/{slug}','Client\SlideController@show');
});

BanhCuonPhuongAnh.laravel/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
	use SoftDeletes;
	protected $fillable = [
        'name', 'product_category_id', 'image','status','price','content','description','meta_title','meta_description','meta_keyword'
    ];

    public function product_category(){
    	return $this->belongsTo('App\Product_Category');
    }

    public function hot_product(){
        return $this->hasMany('App\HotProduct');
    }

    public function selective_product(){
        return $this->hasMany('App\SelectiveProduct');
    }

    public function key_words(){
		return $this->belongsTomany('App\Key_Word','products_key_words','product_id','key_word_id')->whereNull('products_key_words.deleted_at')->withTimestamps();
	}

	public function products_photos(){
    	return $this->hasMany('App\ProductsPhoto','product_id');
    }
}

BanhCuonPhuongAnh.laravel/app/Http/Controllers/Client/ProductController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Client\MenuController;
use Illuminate\Http\Request;
use App\Product;
use App\News;
use App\News_Category;
use App\Product_Category;
use App\Configuration;
use App\Menu;

class ProductController extends MenuController
{

    public function getListProduct(){
        $menus              =   Menu::all();  
        $configs            =   Configuration::all();
        $productCategories  =   Product_Category::all();
        $products           =   Peoduct::all();
        $news               =   News::all();
        $menu_parent = $this->getMenus();

        return View('client.product.listproduct',compact('menus','configs','menu_parent','products','news','productCategories'));
    }

    public function getDetailProduct($slug,$hashids){
        $menus              =   Menu::all();  
        $configs            =   Configuration::all();
        $productCategories  =   Product_Category::all();
        $product            =   Product::where('slug',$slug)->first();
        $news               =   News::all();
        
        $menu_parent = $this->getMenus();

        return View('client.product.product',compact('menus','configs','menu_parent','product','news','productCategories'));
    }

    public function getProductSameTag($slug){
        $productCategories  =   Product_Category::all();
        $menus              =   Menu::all();  
        $configs            =   Configuration::all();
        $products           =   Product::all();
        $news               =   News::all();
        
        $product_k = [];
        foreach($products as $product){
            foreach($product->key_words as $key_word)
                if($key_word->slug == $slug){
                    array_push($product_k,$product);
                    break;
                }
        }

        $menu_parent = $this->getMenus();

        return View('client.product.productSameTag',compact('menus','configs','menu_parent','products','product_k','news','productCategories'));
    }

    public function getProductSameCategory($slugCategory){
        $menus              =   Menu::all();  
        $configs            =   Configuration::all();
        $productCategories  =   Product_Category::all();
        $productCategory    =   Product_Category::where('slug',$slugCategory)->first();
        $news               =   News::all();
        
        $menu_parent = $this->getMenus();

        return View('client.product.productSameCategory',compact('menus','configs','menu_parent','productCategory','productCategories','news'));
    }

    public function search(Request $request){
        $menus              =   Menu::all();  
        $configs            =   Configuration::all();
        $productCategories  =   Product_Category::all();

        $search = $request->search;

        $products = Product::where('name', 'like', "$search%")->get();
        
        if(!$products){
            $key_word = Key_Word::where('name', 'like', "$search%")->first();
            $products = $key_word->products;
        }

        $news = $this->getNews();
        $menu_parent = $this->getMenus();

        return View('client.product.searchproduct',compact('menus','configs','menu_parent','products','productCategories','news','search'));
    }
}

BanhCuonPhuongAnh.laravel/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\ProductStoreRequest;
use App\Http\Requests\ProductUpdateRequest;
use App\Product_Category;
use App\Product;
use App\Key_Word;
use Illuminate\Support\Facades\Storage;
use Image;
use Hashids\Hashids;
use App\Hot_Product;
use App\Selective_Product;

class ProductController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
        $this->middleware('role');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $product_categories =   Product_Category::all();
        $status             =   $request->status;
        $id                 =   $request->keyword;
        $category_id        =   $request->category_id;
        $action             =   $request->action;

        if($status||($id && $action == 'id')||$category_id){

            // $products = new Product();
            // if($status){
            //     $product = Product::where('status',$status)->get();
            //     $products = $product;
            //     if($id&& $action == 'id'){
            //         $product->where('id',$id);
            //         $products = $product;
            //         if($category_id){
            //             $product->where('product_category_id',$category_id);
            //             $products = $product;
            //         }
            //     }
            //     else{
            //         if($category_id){
            //             $product->where('product_category_id',$category_id);
            //             $products = $product;
            //         }
            //     }
            // }
            // else{
            //     if($id&& $action == 'id'){
            //         $product = Product::where('id',$id)->get();
            //         if($category_id){
            //             $product->where('product_category_id',$category_id);
            //             $products = $product;
            //         }
            //     }
            //     else{
            //         if($category_id){
            //             $product->where('product_category_id',$category_id)->get();
            //             $products = $product;
            //         }
            //     }
            // }


            if($category_id && ($id && $action == 'id') && $status){
                $products = Product::where('status',$status)->where('product_category_id',$category_id)->where('id',$id)->get();
            }
            elseif($status && ($id && $action == 'id')){
                $products = Product::where('status',$status)->where('id',$id)->get();
            }
            elseif($category_id && ($id && $action == 'id')){
                $products = Product::where('id',$id)->where('product_category_id',$category_id)->get();
            }
            elseif($status && $category_id){
                $products = Product::where('status',$status)->where('product_category_id',$category_id)->get();
            }
            elseif($id && $action == 'id'){
                $products = Product::where('id',$id)->get();
            }
            elseif($category_id){
                $products = Product::where('product_category_id',$category_id)->get();
            }else{
                $products = Product::where('status',$status)->get();
            }
            
            return View('admin.product.product.index',compact('products','product_categories','status','id','category_id','action'));
        }

        $products    = Product::all();
        $status             =   "";
        $id                 =   "";
        $category_id        =   "";
        return View('admin.product.product.index',compact('products','product_categories','status','id','category_id','action'));    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product_categories = Product_Category::all();
        $key_words          = Key_Word::all();
        return View('admin.product.product.create',compact('product_categories','key_words'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductStoreRequest $request)
    {
        $product                      = new Product();
        $product->name                = $request->name;
        $product->slug                = $request->slug;
        $product->content             = $request->content;
        $product->description         = $request->description;
        $product->product_category_id = $request->product_category_id;
        $product->price               = $request->price;
        $product->meta_title          = $request->meta_title;
        $product->meta_description    = $request->meta_description;
        $product->meta_keyword        = $request->meta_keyword;
        $product->status              = $request->filled('status');

        try {
            
            $product->save();
            // $hashids = new Hashids('', 6);
            // $hashids->encode(6));
            if($request->key_words){ 
                foreach ($request->key_words as $key_word) {
                    $product->key_words()->attach($key_word);
                }
            }
            return redirect()->route('product.index');  
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product_categories = Product_Category::all();
        $product            = Product::find($id);
        $key_words          = Key_Word::all();
        return View('admin.product.product.see',compact('product_categories','product','key_words'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product            = Product::find($id);
        $product_categories = Product_Category::all();
        $key_words          = Key_Word::all();
        return View('admin.product.product.edit',compact('product','product_categories','key_words'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductUpdateRequest $request, $id)
    {
        $product                      = Product::find($id);
        $product->name                = $request->name;
        $product->slug                = $request->slug;
        $product->content             = $request->content;
        $product->description         = $request->description;
        $product->product_category_id = $request->product_category_id;
        $product->price               = $request->price;
        $product->meta_title          = $request->meta_title;
        $product->meta_description    = $request->meta_description;
        $product->meta_keyword        = $request->meta_keyword;
        $product->status              = $request->filled('status');
        $hashids = new Hashids('', 6);
        $product->hashids = $hashids->encode($product->id);
        if ($request->hasFile('image')){
            $imagePath = $request->file('image')->store('public/images');
            $image = Image::make(Storage::get($imagePath))->resize(300,300)->encode();
            Storage::put($imagePath,$image);
            $imagePath = explode('/',$imagePath);
            $imagePath = $imagePath[2];
            $product->image = $imagePath;
        }
        try {
            $product->save();
            if($request->key_words){ 
                $product->key_words()->detach();
                foreach ($request->key_words as $key_word) {
                    $product->key_words()->attach($key_word);
                }
            }
            return redirect()->route('product.index');  
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product             = Product::find($id);
        $product->delete();

        $product->key_words()->detach();

        foreach($product->products_photos as $products_photo)
        {
            $products_photo->delete();
        }

        if($product->hot_product)
        {
            $product->hot_product->delete();
        }elseif($product->selective_product){
            $product->selective_product->delete();
        }
        
        return redirect()->route('product.index'); 
    }
}

BanhCuonPhuongAnh.laravel/resources/views/admin/product/product/index.blade.php
@extends('admin.layouts.master')
@section('meta_javascript')
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="6QPUtq9xy8PQzRCTYJFBr3t7UufEuAk2lX98N111">
    <script>
        var csrf_token = '6QPUtq9xy8PQzRCTYJFBr3t7UufEuAk2lX98N111';
    </script>
@endsection
@section('title','banhcuonphuonganh.com')
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>Danh sách Sản phẩm</h2>
            <ol class="breadcrumb">
                <li><a href="route('product.index')">Trang chủ</a></li>
            </ol>
        </div>
    </div>

    
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">

                        <div class="row">
                            <form method="GET" action="{{route('product.index')}}" accept-charset="UTF-8" id="search-frm" class="form-horizontal">
                                <div class="col-lg-4">
                                    <div class="btn-group">
                                        <button data-toggle="dropdown" class="btn btn-default dropdown-toggle">Hành động <span
                                                    class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a href="{{route('selective.store')}}" class="_check_add_to"
                                                   data-target="_list"><i class="fa fa-plus"></i> Chọn lọc</a></li>
                                            <li><a href="{{route('hot.store')}}" class="_check_add_to" data-target="_list"><i class="fa fa-plus"></i> Hot</a></li>
                                        </ul>
                                    </div>

                                    <a href="{{route('product.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i> Thêm</a>
                                </div>
                                <div class="col-lg-2" style="padding-right: 0;">
                                    <select class="form-control chosen-select" data-placeholder="Chọn Trạng thái" onchange="$('#search-frm').submit();" name="status">
                                        @if($status)
                                            <option value="" >Chọn Trạng thái</option>
                                            <option value="1" selected="selected">Xuất bản</option>
                                            <option value="0">Chưa xuất bản</option>
                                        @elseif($status == 0)
                                            <option value="" >Chọn Trạng thái</option>
                                            <option value="1">Xuất bản</option>
                                            <option value="0" selected="selected">Chưa xuất bản</option>
                                        @else
                                            <option value="" selected="selected">Chọn Trạng thái</option>
                                            <option value="1">Xuất bản</option>
                                            <option value="0" >Chưa xuất bản</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="col-lg-3" style="padding-right: 0;">
                                    <select class="form-control chosen-select" data-placeholder="Chọn Thể loại" 
                                    onchange="$('#search-frm').submit();" name="category_id">
                                        <option value="0" selected="selected">Chọn Thể loại</option>
                                        @foreach($product_categories as $cat)
                                            @if($cat->id == $category_id)
                                                <option value="{{$cat->id}}" selected="selected">{{$cat->name}}</option>
                                            @else 
                                                <option value="{{$cat->id}}">{{$cat->name}}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-lg-3">
                                    <div class="input-group">
                                        <input class="form-control" placeholder="Tìm kiếm" autocomplete="off" name="keyword" type="text" value="{{ $id ? $id : ''}}">

                                        <input type="hidden" name="action" id="search-action" value="id"/>

                                        <div class="input-group-btn">
                                            <button data-toggle="dropdown" class="btn btn-white dropdown-toggle"
                                                    type="button" aria-expanded="false"><i class="fa fa-search"></i>
                                            </button>
                                            <ul class="dropdown-menu pull-right">
                                                <li><a href="#" class="action" 
                                                       onclick='$("#search-action").val("id");$("#search-frm").submit();'>Tìm
                                                        theo ID</a></li>
                                                <li><a href="#"
                                                       onclick='$("#search-action").val("eid");$("#search-frm").submit();'>Tìm
                                                        theo ID Mã hóa</a>
                                                </li>
                                                <li class="divider"></li>
                                                <li><a href="#"
                                                       onclick='$("#search-action").val("title");$("#search-frm").submit();'>Tìm
                                                        theo Tiêu đề</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <table id='_list' class="table table-bordered">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" value="" class="check_all"></th>
                                    <th>ID</th>
                                    <th>Hình ảnh</th>
                                    <th>Tiêu đề</th>
                                    <th>Thể loại</th>
                                    <th>Trạng thái</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                 @foreach($products as $pro)                                   
                                    <tr>
                                        <td><input type="checkbox" value="{{$pro->id}}" name = check_item[] class="check_item"></td>
                                        <td>{{$pro->id}}</td>
                                        <td width="150">
                                            <img src="{{Storage::url('images/'.$pro->image)}}" alt="" width="150px" height="100px">
                                        </td>
                                        <td>
                                            <a target="_blank" href="{{'http://banhcuonphuonganh.com/'.$pro->slug.','.$pro->hashids}}">
                                                <h4>{{$pro->name}}</h4>
                                            </a>
                                            <p>{{$pro->created_at}}</p>
                                        </td>
                                        <td>
                                            @if($pro->product_category)
                                                {{$pro->product_category->name}}
                                            @else
                                                
                                            @endif
                                        </td>
                                        <td>
                                            @if($pro->status == 1)
                                                <span class="text-success">Xuất bản</span>
                                            @else
                                                <span class="text-warning">Chưa xuất bản</span>
                                            @endif
                                        </td>
                                        <td width="150">
                                            <ul style="list-style-type:none; padding: 0px; margin:0">
                                                <li style="float:left; margin-top: 6px">
                                                    <a class="btn btn-white btn-bitbucket" style="padding:6px 8px" href="{{route('product.show',$pro->id)}}" title="Xem" data-toggle="tooltip" data-placement="top" data-original-title="Xem"><i class="fa fa-search"></i></a>
                                                </li>
                                                <li style="float:left; margin-top: 6px; margin-left: 16px">
                                                    <a class="btn btn-white btn-bitbucket" style="padding:6px 8px" href="{{route('product.edit',$pro->id)}}" title="Sửa" data-toggle="tooltip" data-placement="top" data-original-title="Sửa"><i class="fa fa-pencil"></i></a>
                                                </li>
                                                <li style="float:right; margin-top: 6px">
                                                    <form method="POST" action="{{route('product.destroy',$pro->id)}}" accept-charset="UTF-8">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="btn btn-white btnDelete" style="padding:6px 8px" title="Xóa" data-toggle="tooltip"data-placement="top" data-original-title="Xóa"><i class="fa fa-trash"></i></button>
                                                    </form>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="clearfix">
                            <div class="pull-right"></div>
                        </div>
                        <!-- -->
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('javascript')
    <script type="text/javascript">
        $(".btnDelete").click(function (){
          var isDelete = confirm('Are you sure want to delete ?');
          if(isDelete){
            return true;
          }else{
            return false;
          }
        });
    

        $('body').tooltip({
            selector: "[data-toggle=tooltip]",
            container: "body"
        });

        $('table').on('click', ".check_all", function () {
            var checked = $('.check_all').is(':checked');
            $(this).closest('table').find('.check_item').each(function () {
                if ($(this).is(':checked') != checked)
                    $(this).click();
            });
        });

        $('._check_add_to').click(function () {
            var _url = $(this).attr('href'), _target = $('#' + $(this).data('target')), _items = new Array();
            var link =
            _target.find("input[type=checkbox]:checked").each(function () {
                if ('' != $(this).val())
                    _items.push(parseInt($(this).val()));
            });

            App.ajax({
                url: _url,
                type: 'post',
                data: {
                    ids: _items,
                    '_token': '{!! csrf_token() !!}',
                },
                success: function (data) {
                    window.location.href = data
                }
            });

            return false;
        });
</script>
@endsection