BanhCuonPhuongAnh.laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::group(['domain'=>'cms.banhcuonphuonganh.com'],function(){

	Route::prefix('product')->group(function(){
		Route::resource('/category','ProductCategoryController');
		Route::resource('/gallery','ProductPhotoController');
		Route::resource('/hot','HotProductController');
		Route::resource('/selective','SelectiveProductController');
	});
	 
	Route::resource('/product','ProductController');
	Route::resource('/','ProductController');
	
	Route::resource('/tag','KeyWordController');

	Route::prefix('post')->group(function(){
		// Route::resource('/category','PostCategoryController');
		Route::get('/category/create', 'PostCategoryController@create')->name('postcategory.create');
		Route::get('/category', 'PostCategoryController@index')->name('postcategory.index');
		Route::post('/category', 'PostCategoryController@store')->name('postcategory.store');
		Route::delete('/category/{category}', 'PostCategoryController@destroy')->name('postcategory.destroy');
		Route::get('/category/{category}/edit', 'PostCategoryController@edit')->name('postcategory.edit');
		Route::patch('/category/{category}', 'PostCategoryController@update')->name('postcategory.update');
		Route::get('/category/{category}', 'PostCategoryController@show')->name('postcategory.show');
	});
	 
	Route::resource('/post','PostController');

	Route::prefix('news')->group(function(){
		Route::get('/category/create', 'NewsCategoryController@create')->name('newscategory.create');
		Route::get('/category', 'NewsCategoryController@index')->name('newscategory.index');
		Route::post('/category', 'NewsCategoryController@store')->name('newscategory.store');
		Route::delete('/category/{category}', 'NewsCategoryController@destroy')->name('newscategory.destroy');
		Route::get('/category/{category}/edit', 'NewsCategoryController@edit')->name('newscategory.edit');
		Route::patch('/category/{category}', 'NewsCategoryController@update')->name('newscategory.update');
		Route::get('/category/{category}', 'NewsCategoryController@show')->name('newscategory.show');
		Route::get('/category/image-crop-upload', 'NewsCategoryController@cropUploadImage');
	});
	 
	Route::resource('/news','NewsController');
	Route::resource('/config','ConfigurationController');
	Route::resource('/user','UserController');

	Route::prefix('menu')->group(function(){
		Route::get('/order','MenuController@order')->name('menu.order');
		Route::post('/orderStore','MenuController@orderStore')->name('menuorder.store');
	});
	Route::resource('/menu','MenuController');

	Route::resource('/slide','SlideController');


	Auth::routes();
	Route::get('/user/verify/{confirmation_code}','Auth\RegisterController@verifyUser')->name('activate.user');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::delete('/deleteRecord/{id}','ProductPhotoController@deleteRecord');
});

Route::group(['domain'=>'banhcuonphuonganh.com'],function(){
	Route::get('/','Client\HomeController@index');
	Route::get('/bai-viet/{slug}','Client\PostController@getDetailPost');

	//Route::get('/tin-tuc/{slug1}/{slug2}','Client\NewsController@getDetailNews');
	Route::get('{slug},{news_id}','Client\NewsController@getDetailNews')->where(['news_id' => '.{4}']);
	Route::get('/tin-tuc/{slug}','Client\NewsController@getNewsSameCategory');
	Route::get('/tin-tuc','Client\NewsController@getListNews');

	Route::get('{slug},{product_id}','Client\ProductController@getDetailProduct')->where(['product_id' => '.{6}']);
	Route::get('/san-pham/{slug}','Client\ProductController@getProductSameCategory');
	Route::get('/tag/{slug}','Client\ProductController@getProductSameTag');
	Route::get('/san-pham','Client\ProductController@getListProduct');
	Route::get('/tim-kiem','Client\ProductController@search');
	// Route::get('/slide/{slug}','Client\SlideController@show');
});

BanhCuonPhuongAnh.laravel/app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slide extends Model
{
    use SoftDeletes;
}

BanhCuonPhuongAnh.laravel/app/Http/Controllers/SlideController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\SlideStoreRequest;
use App\Http\Requests\SlideUpdateRequest;
use App\Slide;
use Illuminate\Support\Facades\Storage;
use Image;

class SlideController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
        $this->middleware('role');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slides = Slide::paginate(10);
        return View('admin.other_information.slide.index',compact('slides'));    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('admin.other_information.slide.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SlideStoreRequest $request)
    {
        $slide                     = new Slide();
        $slide->name               = $request->name;
        $slide->url                = $request->url;
        $slide->description        = $request->description;
        try {
            $slide->save();
            return redirect()->route('slide.index');  
        } catch (Exception $e) {
            die($e->getMessage());
        }    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $slide   = Slide::find($id);
        return View('admin.other_information.slide.see',compact('slide'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slide    = Slide::find($id);
        return View('admin.other_information.slide.edit',compact('slide'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SlideUpdateRequest $request, $id)
    {
        $slide                     = Slide::find($id);
        $slide->name               = $request->name;
        $slide->url                = $request->url;
        $slide->description        = $request->description;

        if ($request->hasFile('image')){
            $imagePath = $request->file('image')->store('public/images');
            $image = Image::make(Storage::get($imagePath))->resize(300,300)->encode();
            Storage::put($imagePath,$image);
            $imagePath = explode('/',$imagePath);
            $imagePath = $imagePath[2];
            $slide->image = $imagePath;
        }

        try {
            $slide->save();
            return redirect()->route('slide.index');  
        } catch (Exception $e) {
            die($e->getMessage());
        }    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slide             = Slide::find($id);
        try {
            $slide->delete();
            return redirect()->route('slide.index'); 
        } catch (Exception $e) {
            die($e->getMessage());
        }  
    }
}

BanhCuonPhuongAnh.laravel/resources/views/admin/other_information/slide/create.blade.php
@extends('admin.layouts.master')
@section('meta_javascript')
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD">
    <script>
        var csrf_token = 'vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD';
    </script>
@endsection
@section('title','Thêm Slide')
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>Thêm Slide</h2>
            <ol class="breadcrumb">
                <li><a href="{{route('product.index')}}">Trang chủ</a></li>
                <li><a href="{{route('slide.index')}}">Danh sách Tin tức</a></li>
                <li>Thêm slide</li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <form method="POST" action="{{route('slide.store')}}" accept-charset="UTF-8" class="form-horizontal">
                        @csrf
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">Slide:</label>
                            <div class="col-sm-10">
                                <input class="form-control" placeholder="Tên Slide" autocomplete="off" name="name" type="text" value="{{old('name')}}" id="title">
                                <span class="text-danger">{{ $errors->first('name')}}</span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="url" class="col-sm-2 control-label">Url:</label>
                            <div class="col-sm-10">
                                <input class="form-control" placeholder="Url" autocomplete="off" name="url" type="text" value="{{old('url')}}" id="url">
                                <span class="text-danger">{{ $errors->first('url')}}</span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="description" class="col-sm-2 control-label">Mô tả:</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" name="description" cols="50" rows="10" id="description">{{old('description')}}</textarea>
                                <span class="text-danger">{{ $errors->first('description')}}</span>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-2"></div>
                            <div class="col-sm-10">
                                <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Thêm
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

BanhCuonPhuongAnh.laravel/resources/views/admin/other_information/slide/edit.blade.php
@extends('admin.layouts.master')
@section('meta_javascript')
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="5loXHGehGmtCsWmIakTOsoidgy8QHc3YEGk62cAc">
    <script>
        var csrf_token = '5loXHGehGmtCsWmIakTOsoidgy8QHc3YEGk62cAc';
    </script>
@endsection
@section('title',$slide->name)
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>{{$slide->name}}</h2>
            <ol class="breadcrumb">
                <li><a href="{{route('product.index')}}">Trang chủ</a></li>
                <li><a href="{{route('slide.index')}}">Danh sách Tin tức</a></li>
                <li><a href="{{route('slide.show',$slide->id)}}">Xem chi tiết</a></li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content">
        <div class="col-lg-12">
            <form method="POST" action="{{route('slide.update',$slide->id)}}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="row">
                    <div class="tabs-container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true"> Thông tin chi tiết</a>
                            </li>
                            <li class=""><a data-toggle="tab" href="#tab-2" aria-expanded="false">Ảnh đại diện</a>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="name" class="col-sm-2 control-label">Slide:</label>

                                            <div class="col-sm-10">
                                                <input class="form-control" placeholder="Tên Slide" name="name" type="text" value="{{$slide->name}}" id="title">
                                                <span class="text-danger">{{ $errors->first('name')}}</span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="url" class="col-sm-2 control-label">Url:</label>

                                            <div class="col-sm-10">
                                                <input class="form-control" placeholder="Url" name="url" type="text" value="{{$slide->url}}" id="url">
                                                <span class="text-danger">{{ $errors->first('url')}}</span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="description" class="col-sm-2 control-label">Mô tả:</label>
                                            <div class="col-sm-10">
                                                <textarea class="form-control" name="description" cols="50" rows="10" id="description">{{$slide->description}}</textarea>
                                                <span class="text-danger">{{ $errors->first('description')}}</span>
                                            </div>
                                        </div>

                                        <div class="hr-line-dashed"></div>

                                        <div class="form-group">
                                            <div class="col-sm-2"></div>
                                            <div class="col-sm-10">
                                                <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Cập nhật
                                                </button>
                                            </div>
                                        </div>
                                        <input type="hidden" name="slide_id" value="{{$slide->id}}">
                                    </div>
                                </div>
                            </div>
                            <div id="tab-2" class="tab-pane">
                                <div class="panel-body">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="files" style="width:120px;margin-top: 25px" class="btn btn-primary btn-block btn-outlined">Select Image</label>
                                            <input type="file" style="visibility:hidden;" name="image" class="form-file-control" id ="files" onchange="previewFile();">
                                            <img id = "preview" src="{{Storage::url('images/'.$slide->image)}}">
                                            <span class="text-danger">{{ $errors->first('image') }}</span>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-2"></div>
                                            <div class="col-sm-10">
                                                <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Cập nhật
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection
@section('javascript')
    <script> 
        function previewFile(){ 
            var preview = $('#preview');
            var file = $('#files').prop('files')[0];
            var reader = new FileReader();
            if(file){
                reader.readAsDataURL(file);
            }else{
                preview.attr('src', '');
            }
            reader.onloadend = function() {
                preview.attr('src', reader.result);
            }
        }
    </script>
@endsection

BanhCuonPhuongAnh.laravel/resources/views/admin/other_information/slide/index.blade.php
@extends('admin.layouts.master')
@section('meta_javascript')
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD">
    <script>
        var csrf_token = 'vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD';
    </script>
@endsection
@section('title','Danh sách slide')
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>Danh sách Slide</h2>
            <ol class="breadcrumb">
                <li><a href="{{route('product.index')}}">Trang chủ</a></li>
                <li>Danh sách Slide</li>
            </ol>
        </div>
    </div>
    
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">

                        <div class="row">
                            <div class="col-lg-12">
                                <a href="{{route('slide.create')}}" class="btn btn-primary "><i class="fa fa-plus"></i> Thêm</a>
                            </div>
                        </div>
                        <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Slide</th>
                                        <th width="200"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($slides as $slide)
                                        <tr>
                                            <td width="150">
                                                <img src="{{Storage::url('images/'.$slide->image)}}" alt="" width="150px" height="100px"/>
                                            </td>
                                            <td>{{$slide->name}}</td>
                                            <td width="150">
                                                <ul style="list-style-type:none; padding: 0px; margin:0">
                                                        <li style="float:left; margin-top: 6px">
                                                            <a class="btn btn-white btn-bitbucket" style="padding:6px 8px" href="{{route('slide.show',$slide->id)}}" title="Xem" data-toggle="tooltip" data-placement="top" data-original-title="Xem"><i class="fa fa-search"></i>Xem</a>
                                                        </li>
                                                        <li style="float:left; margin-top: 6px; margin-left: 2px">
                                                            <a class="btn btn-white btn-bitbucket" style="padding:6px 8px" href="{{route('slide.edit',$slide->id)}}" title="Sửa" data-toggle="tooltip" data-placement="top" data-original-title="Sửa"><i class="fa fa-pencil"></i>Sửa</a>
                                                        </li>
                                                        <li style="float:right; margin-top: 6px">
                                                            <form method="POST" action="{{route('slide.destroy',$slide->id)}}" accept-charset="UTF-8">
                                                                @csrf
                                                                @method('DELETE')
                                                                <button class="btn btn-white btnDelete" style="padding:6px 8px" title="Xóa" data-toggle="tooltip"data-placement="top" data-original-title="Xóa"><i class="fa fa-trash"></i>Xóa</button>
                                                            </form>
                                                        </li>
                                                </ul>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                        </table>   
                        <div style="float: right">
                            {{ $slides->links() }}
                        </div>     
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script type="text/javascript">
        $(".btnDelete").click(function (){
          var isDelete = confirm('Are you sure want to delete ?');
          if(isDelete){
            return true;
          }else{
            return false;
          }
        });
    </script>
@endsection

BanhCuonPhuongAnh.laravel/resources/views/admin/other_information/slide/see.blade.php
@extends('admin.layouts.master')
@section('meta_javascript')
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="5loXHGehGmtCsWmIakTOsoidgy8QHc3YEGk62cAc">
    <script>
        var csrf_token = '5loXHGehGmtCsWmIakTOsoidgy8QHc3YEGk62cAc';
    </script>
@endsection
@section('title','banhcuonphuonganh.com')
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>{{$slide->name}}</h2>
            <ol class="breadcrumb">
                <li><a href="{{route('product.index')}}">Trang chủ</a></li>
                <li><a href="{{route('slide.index')}}">Danh sách Tin tức</a></li>
                <li><a href="{{route('slide.edit',$slide->id)}}">Sửa thông tin</a></li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content">

        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Thông tin chi tiết</h5>
                </div>
                <div class="ibox-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <th width="150px">#</th>
                                <th>Giá trị</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>ID</td>
                                <td>{{$slide->id}}</td>
                            </tr>
                            <tr>
                                <td>Bài viết</td>
                                <td>{{$slide->name}}</td>
                            </tr>
                            <tr>
                                <td>Mô tả</td>
                                <td>{{$slide->description}}</td>
                            </tr>
                            <tr>
                                <td>Tạo bởi</td>
                                <td>admin vào lúc {{$slide->created_at}}</td>
                            </tr>
                            <tr>
                                <td>Cập nhật bởi</td>
                                <td>admin vào lúc {{$slide->updated_at}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
@endsection