NVThien/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return 'welcome haha';
});

Route::resource('/users','UserController');
Route::resource('/department','DepartmentController');

Auth::routes();
Route::get('/user/verify/{confirmation_code}','Auth\RegisterController@verifyUser')->name('activate.user');


Route::get('/home', 'HomeController@index')->name('home');
Route::prefix('ajax')->group(function () {
    Route::get('/viewList','MemberController@getViewList')->name('ajax.viewList');
	Route::get('/viewDetail/{id}','MemberController@getViewDetail')->name('ajax.viewDetail');
	Route::get('/viewDetailSamDep/{id}','MemberController@getViewDetailSamDep')->name('ajax.viewDetailSamDep');
	Route::post('/updateUsers{id}','MemberController@updateUsers')->name('ajax.updateUsers');
});


Route::post('/post-login','Auth\UserLoginController@login')->name('post-login');

NVThien/app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Department extends Model
{
	use SoftDeletes;
    public $table = "department";

    public function users(){
    	return $this->hasMany('App\Users');
    }

}

NVThien/app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\DepartmentStoreRequest;
use App\Http\Requests\DepartmentUpdateRequest;
use App\Department;

class DepartmentController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
        $this->middleware('role:Admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $department = Department::paginate(1);
        return view('admin.department.index',compact('department'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DepartmentStoreRequest $request)
    {
        $dep = new Department();
        $dep->name = $request->name;
        try {
            $dep->save();
            return redirect()->route('department.index');
        } catch (Exception $e) {
            echo $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department)
    {//var_dump($department);die();
        return view('admin.department.edit',compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DepartmentUpdateRequest $request, Department $department)
    {
        // var_dump('haha');die();
        $department->name = $request->name;
        try {
            $department->save();
            return redirect()->route('department.index');
        } catch (Exception $e) {
            echo $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department)
    {
        try {
            $department->deleted_at = date('Y-m-d H:i:s');
            $department->save();
            //$department->delete();
            return redirect()->route('department.index');
            
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }
}

NVThien/resources/views/admin/department/create.blade.php
@extends('admin.layouts.master')
@section('title','Department Create')
@section('content')

	<div class="content container">
		<form id="create_dep" method="post" autocomplete="off" action="{{route('department.store') }}" >
			@csrf
			<div class="row">
				<div class="title col-md-3"><h3>Create Department</h3></div>
				<div class="nav-function col-md-3 col-md-offset-6">
					<h3>
						<button id="btn-submit" class="btn btn-primary" style="float: right; margin-left: 5px">Save</button>
						<a href="{{route('department.index') }}" class="btn btn-warning" style="float: right;">Back</a>
					</h3>
				</div>
			</div>
			<div class="form-group">
		    	<label for="name">Name</label>
		    	<input type="text" id="name" required autocomplete="off" class="form-control" name="name" placeholder="Name" value="{{ old('name') }}">
				<span class="text-danger">{{ $errors->first('name') }}</span> 	
			</div>
		</form>
	</div>
@endsection
@section('javascript')
	<script type="text/javascript" src="{{ asset('js/jquery.validate.min.js') }}"></script>
	<!-- <script type="text/javascript" src="{{ asset('js/validate.js') }}"></script> -->
	
	<!-- <script type="text/javascript">
		$('#name').keyup(function(){
		    html='';
		    $('#nameError1').html(html);
		    $("#nameError1").removeClass('alert alert-danger');
		});

		$('#btn-submit').click(function (){
	    	$('#nameError1').html('');
	    	var name = $('#name').val();
	   		$.ajax({
	        	url : 'index.php?url=DepartmentController/checkName',
	        	type : 'post',
	        	dataType : 'json',
	        	data : {
	            	name : name,      
	        	},
	        	success : function (result){
		            var html = '';
		            if (result.error == true){
		                html += result.message;
		            }

		            if (html != ''){
		                $('#nameError1').append(html);
		                $('#nameError1').addClass('alert alert-danger');
		            }
		            else {
		                $('form').submit();
		            }
		        }
		    });
	    	return false;
		});
	</script> -->
@endsection
	

NVThien/resources/views/admin/department/edit.blade.php
@extends('admin.layouts.master')
@section('title','Departmant Edit')
@section('content')

	<div class="content container">
		<form id="edit_dep" autocomplete="off" method="post" action="{{route('department.update',$department->id) }}" >
			@csrf
			@method('PUT')
			<div class="row">
				<div class="Name col-md-3"><h3>Edit Department</h3></div>
				<div class="nav-function col-md-3 col-md-offset-6">
					<h3>
						<button type="submit" class="btn btn-primary" style="float: right; margin-left: 5px">Save</button>
						<a href="{{route('department.index') }}" class="btn btn-warning" style="float: right;">Back</a>
					</h3>
				</div>
			</div>
			<div class="form-group">
		    	<label for="name">Name</label>
		    	<input type="text" required autocomplete="off" class="form-control" name="name" placeholder="Name" value="{{$department->name }}">
				<span class="text-danger">{{ $errors->first('name')}}</span>
				<input type="hidden" value="{{ $department->id }}" name="department_id">
			</div>
		  	
		</form>
	</div>
@endsection 
<!-- @section('javascript')

@endsection -->

NVThien/resources/views/admin/department/index.blade.php
@extends('admin.layouts.master')
@section('title','Department Index')
@section('content')

  <div class="content container-fluid">
    <h2>List Department</h2>
    <div class="control clear-fix">
      <a class="btn btn-primary create" href="{{route('department.create')}}">Create</a>
    </div>
    <table class="table table-stripped">
      <tbody>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Created at</th>
          <th>updated at</th>
          <th></th>
          <th></th>
        </tr>
        @foreach($department as $dep)
          <tr>
          <td>{{$dep->id}}</td>
          <td>{{$dep->name}}</td>
          <td>{{$dep->created_at}}</td>
          <td>{{$dep->updated_at}}</td>
          <td>
            <a href="{{route('department.edit',$dep->id)}}" class="btn btn-success btn-mini pull-left">Edit</a>
          </td>
          <td>
              <form method="POST" action="{{route('department.destroy',$dep->id)}}" accept-charset="UTF-8">
                @csrf
                @method('DELETE')
              <button type="submit" class="btnDelete btn btn-danger btn-mini">Delete</button>
              </form>
          </td>
          </tr>
        @endforeach
      </tbody>
    </table>

    <div style="float: right">
      {{ $department->links() }}
    </div>

  </div>
@endsection
@section('javascript')
  <script type="text/javascript">
    $(".btnDelete").click(function (){
      var isDelete = confirm('Are you sure want to delete ?');
      if(isDelete){
        return true;
      }else{
        return false;
      }
    });
  </script>
@endsection