BanhCuonPhuongAnh.laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::group(['domain'=>'cms.banhcuonphuonganh.com'],function(){

	Route::prefix('product')->group(function(){
		Route::resource('/category','ProductCategoryController');
		Route::resource('/gallery','ProductPhotoController');
		Route::resource('/hot','HotProductController');
		Route::resource('/selective','SelectiveProductController');
	});
	 
	Route::resource('/product','ProductController');
	Route::resource('/','ProductController');
	
	Route::resource('/tag','KeyWordController');

	Route::prefix('post')->group(function(){
		// Route::resource('/category','PostCategoryController');
		Route::get('/category/create', 'PostCategoryController@create')->name('postcategory.create');
		Route::get('/category', 'PostCategoryController@index')->name('postcategory.index');
		Route::post('/category', 'PostCategoryController@store')->name('postcategory.store');
		Route::delete('/category/{category}', 'PostCategoryController@destroy')->name('postcategory.destroy');
		Route::get('/category/{category}/edit', 'PostCategoryController@edit')->name('postcategory.edit');
		Route::patch('/category/{category}', 'PostCategoryController@update')->name('postcategory.update');
		Route::get('/category/{category}', 'PostCategoryController@show')->name('postcategory.show');
	});
	 
	Route::resource('/post','PostController');

	Route::prefix('news')->group(function(){
		Route::get('/category/create', 'NewsCategoryController@create')->name('newscategory.create');
		Route::get('/category', 'NewsCategoryController@index')->name('newscategory.index');
		Route::post('/category', 'NewsCategoryController@store')->name('newscategory.store');
		Route::delete('/category/{category}', 'NewsCategoryController@destroy')->name('newscategory.destroy');
		Route::get('/category/{category}/edit', 'NewsCategoryController@edit')->name('newscategory.edit');
		Route::patch('/category/{category}', 'NewsCategoryController@update')->name('newscategory.update');
		Route::get('/category/{category}', 'NewsCategoryController@show')->name('newscategory.show');
		Route::get('/category/image-crop-upload', 'NewsCategoryController@cropUploadImage');
	});
	 
	Route::resource('/news','NewsController');
	Route::resource('/config','ConfigurationController');
	Route::resource('/user','UserController');

	Route::prefix('menu')->group(function(){
		Route::get('/order','MenuController@order')->name('menu.order');
		Route::post('/orderStore','MenuController@orderStore')->name('menuorder.store');
	});
	Route::resource('/menu','MenuController');

	Route::resource('/slide','SlideController');


	Auth::routes();
	Route::get('/user/verify/{confirmation_code}','Auth\RegisterController@verifyUser')->name('activate.user');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::delete('/deleteRecord/{id}','ProductPhotoController@deleteRecord');
});

Route::group(['domain'=>'banhcuonphuonganh.com'],function(){
	Route::get('/','Client\HomeController@index');
	Route::get('/bai-viet/{slug}','Client\PostController@getDetailPost');

	//Route::get('/tin-tuc/{slug1}/{slug2}','Client\NewsController@getDetailNews');
	Route::get('{slug},{news_id}','Client\NewsController@getDetailNews')->where(['news_id' => '.{4}']);
	Route::get('/tin-tuc/{slug}','Client\NewsController@getNewsSameCategory');
	Route::get('/tin-tuc','Client\NewsController@getListNews');

	Route::get('{slug},{product_id}','Client\ProductController@getDetailProduct')->where(['product_id' => '.{6}']);
	Route::get('/san-pham/{slug}','Client\ProductController@getProductSameCategory');
	Route::get('/tag/{slug}','Client\ProductController@getProductSameTag');
	Route::get('/san-pham','Client\ProductController@getListProduct');
	Route::get('/tim-kiem','Client\ProductController@search');
	// Route::get('/slide/{slug}','Client\SlideController@show');
});

BanhCuonPhuongAnh.laravel/app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
    use SoftDeletes;

    public function news_category(){
    	return $this->belongsTo('App\News_Category');
    }
}

BanhCuonPhuongAnh.laravel/app/News_Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class News_Category extends Model
{
    use SoftDeletes;
    public $table = "news_categories";

    public function news(){
    	return $this->hasMany('App\News','news_category_id');
    }
}

BanhCuonPhuongAnh.laravel/app/Http/Controllers/Client/NewsController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Client\MenuController;
use Illuminate\Http\Request;
use App\Product;
use App\News;
use App\News_Category;
use App\Configuration;
use App\Menu;

class NewsController extends MenuController
{

    public function getListNews(){
        $menus              =   Menu::all();
        $newsCategories     =   News_Category::all();
        $configs            =   Configuration::all();
        $news               =   News::all();

        $menu_parent = $this->getMenus();

        return View('client.news_event.listNews',compact('menus','configs','menu_parent','news','newsCategories'));
    }

    public function getDetailNews($slug,$hashids){
        $menus              =   Menu::all();  
        $configs            =   Configuration::all();
        $newsCategories     =   News_Category::all();
        $newsDetail         =   News::where('slug',$slug)->first();
        
        $menu_parent = $this->getMenus();

        return View('client.news_event.detailNews',compact('menus','configs','menu_parent','newsDetail','newsCategories'));
    }

    public function getNewsSameCategory($slugCategory){
        $menus              =   Menu::all();  
        $configs            =   Configuration::all();
        $newsCategories     =   News_Category::all();
        $newsCategory       =   News_Category::where('slug',$slugCategory)->first();

        $menu_parent = $this->getMenus();

        return View('client.news_event.newsSameCategory',compact('menus','configs','menu_parent','newsCategory','newsCategories'));
    }

}

BanhCuonPhuongAnh.laravel/app/Http/Controllers/NewsCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\NewsCategoryStoreRequest;
use App\Http\Requests\NewsCategoryUpdateRequest;
use App\News_Category;

class NewsCategoryController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news_categories = News_Category::paginate(10);
        return View('admin.news.news_categories.index',compact('news_categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('admin.news.news_categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NewsCategoryStoreRequest $request)
    {
        $news                     = new News_Category();
        $news->name               = $request->name;
        $news->slug               = $request->slug;
        $news->description        = $request->description;
        $news->meta_title         = $request->meta_title;
        $news->meta_description   = $request->meta_description;
        $news->meta_keyword       = $request->meta_keyword;

        try {
            $news->save();
            return redirect()->route('newscategory.index');  
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news_categories = News_Category::all();
        $news_category   = News_Category::find($id);
        return View('admin.news.news_categories.edit',compact('news_categories','news_category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NewsCategoryUpdateRequest $request, $id)
    {
        $news                     = News_Category::find($id);
        $news->name               = $request->name;
        $news->slug               = $request->slug;
        $news->description        = $request->description;
        $news->meta_title         = $request->meta_title;
        $news->meta_description   = $request->meta_description;
        $news->meta_keyword       = $request->meta_keyword;

        try {
            $news->save();
            return redirect()->route('newscategory.index');  
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news_category             = News_Category::find($id);
        $news_category->delete();

        foreach($news_category->news as $new)
        {
            $new->delete();
        }
        
        return redirect()->route('newscategory.index');
    }
}

BanhCuonPhuongAnh.laravel/app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\NewsStoreRequest;
use App\Http\Requests\NewsUpdateRequest;
use App\News_Category;
use App\News;
use Illuminate\Support\Facades\Storage;
use Image;
use Hashids\Hashids;

class NewsController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::paginate(10);
        return View('admin.news.news.index',compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $news_categories = News_Category::all();
        return View('admin.news.news.create',compact('news_categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NewsStoreRequest $request)
    {
        $news                     = new News();
        $news->name               = $request->name;
        $news->slug               = $request->slug;
        $news->news_category_id   = $request->news_category_id;
        $news->description        = $request->description;
        $news->content            = $request->content;
        $news->status             = $request->filled('status');
        try {
            $news->save();
            return redirect()->route('news.index');  
        } catch (Exception $e) {
            die($e->getMessage());
        }    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $news   = News::find($id);
        return View('admin.news.news.see',compact('news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news_categories   = News_Category::all();
        $news              = News::find($id);
        return View('admin.news.news.edit',compact('news','news_categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NewsUpdateRequest $request, $id)
    {
        $news                     = News::find($id);
        $news->name               = $request->name;
        $news->slug               = $request->slug;
        $news->news_category_id   = $request->news_category_id;
        $news->description        = $request->description;
        $news->content            = $request->content;
        $news->status             = $request->filled('status');
        $hashids = new Hashids('', 4);
        $news->hashids =  $hashids->encode($news->id);


        if ($request->hasFile('image')){
            $imagePath = $request->file('image')->store('public/images');
            $image = Image::make(Storage::get($imagePath))->resize(300,300)->encode();
            Storage::put($imagePath,$image);
            $imagePath = explode('/',$imagePath);
            $imagePath = $imagePath[2];
            $news->image = $imagePath;
        }

        try {
            $news->save();
            return redirect()->route('news.index');  
        } catch (Exception $e) {
            die($e->getMessage());
        }    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news             = News::find($id);
        try {
            $news->delete();
            return redirect()->route('news.index'); 
        } catch (Exception $e) {
            die($e->getMessage());
        }    
    }
}

BanhCuonPhuongAnh.laravel/resources/views/admin/news/news_categories/create.blade.php
@extends('admin.layouts.master')
@section('meta_javascript')
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD">
    <script>
        var csrf_token = 'vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD';
    </script>
@endsection
@section('title','banhcuonphuonganh.com')
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>Thêm Thể loại</h2>
            <ol class="breadcrumb">
                @if(Auth::user()->level)
                    <li><a href="{{route('product.index')}}">Trang chủ</a></li>
                @else 
                    <li><a href="{{route('post.index')}}">Trang chủ</a></li>
                @endif
                <li><a href="{{route('newscategory.index')}}">Danh sách Thể loại</a></li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Thêm Thể loại</h5>
                    </div>
                    <div class="ibox-content">
                        <form method="POST" action="{{route('newscategory.store')}}" accept-charset="UTF-8" class="form-horizontal">
                            <!-- <input name="_token" type="hidden" value="vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD"> -->
                            @csrf
                            <div class="tabs-container">
                                <ul class="nav nav-tabs">
                                    <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true">Thể loại</a></li>
                                    <li class=""><a data-toggle="tab" href="#tab-3" aria-expanded="false">SEO</a></li>
                                </ul>
                                <div class="tab-content">
                                    <div id="tab-1" class="tab-pane active">
                                        <div class="panel-body">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="name" class="col-sm-2 control-label">Thể loại:</label>
                                                    <div class="col-sm-10">
                                                        <input class="form-control" placeholder="Nhập Thể loại" value="{{old('name')}}" autocomplete="off" name="name" type="text" id="name">
                                                        <span class="text-danger">{{ $errors->first('name')}}</span>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <label for="slug" class="col-sm-2 control-label">Slug:</label>
                                                    <div class="col-sm-10">
                                                        <input class="form-control" name="slug" type="text" autocomplete="off" value="{{old('slug')}}" id="slug">
                                                        <span class="text-danger">{{ $errors->first('slug')}}</span>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <label for="description" class="col-sm-2 control-label">Mô tả:</label>
                                                    <div class="col-sm-10">
                                                        <textarea class="form-control" placeholder="Nhập mô tả" name="description" cols="50" rows="10" id="description">{{old('description')}}</textarea>
                                                        <span class="text-danger">{{ $errors->first('description')}}</span>
                                                    </div>
                                                </div>
                                                <div class="hr-line-dashed"></div>

                                                <div class="form-group">
                                                    <div class="col-sm-2"></div>
                                                    <div class="col-sm-10">
                                                        <button class="btn btn-primary" type="submit"><i class="fa fa-plus"></i> Thêm </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="tab-3" class="tab-pane">
                                        <div class="panel-body">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="meta_title" class="col-sm-2 control-label">Meta title:</label>
                                                    <div class="col-sm-10">
                                                        <input class="form-control" autocomplete="off" value="{{old('meta_title')}}" name="meta_title" type="text" id="meta_title">
                                                        <span class="text-danger">{{ $errors->first('meta_title')}}</span>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <label for="meta_description" class="col-sm-2 control-label">Meta description:</label>
                                                    <div class="col-sm-10">
                                                        <textarea class="form-control" rows="2" name="meta_description" cols="50" id="meta_description">{{old('meta_description')}}</textarea>
                                                        <span class="text-danger">{{ $errors->first('meta_description')}}</span>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <label for="meta_keyword" class="col-sm-2 control-label">Meta keyword:</label>
                                                    <div class="col-sm-10">
                                                        <input class="form-control" autocomplete="off" value="{{old('meta_keyword')}}" name="meta_keyword" type="text" id="meta_keywords">
                                                        <span class="text-danger">{{ $errors->first('meta_keyword')}}</span>
                                                    </div>
                                                </div>

                                                <div class="hr-line-dashed"></div>

                                                <div class="form-group">
                                                    <div class="col-sm-2"></div>
                                                    <div class="col-sm-10">
                                                        <button class="btn btn-primary" type="submit"><i class="fa fa-plus"></i> Thêm </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

BanhCuonPhuongAnh.laravel/resources/views/admin/news/news_categories/edit.blade.php
@extends('admin.layouts.master')
@section('meta_javascript')
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD">
    <script>
        var csrf_token = 'vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD';
    </script>
@endsection
@section('title',$news_category->name)
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>{{$news_category->name}}</h2>
            <ol class="breadcrumb">
                @if(Auth::user()->level)
                    <li><a href="{{route('product.index')}}">Trang chủ</a></li>
                @else 
                    <li><a href="{{route('post.index')}}">Trang chủ</a></li>
                @endif
                <li><a href="{{route('newscategory.index')}}">Danh sách Thể loại</a></li>
                <li>{{$news_category->name}}</li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content">
        <form method="POST" action="{{route('newscategory.update',$news_category->id)}}" accept-charset="UTF-8" class="form-horizontal">
            <!-- <input name="_method" type="hidden" value="PATCH">
            <input name="_token" type="hidden" value="vgyC6rbdRxpxx3ykD9C2Fh0D5fdQCc9vFJtaPcWD"> -->
            @csrf
            @method('PATCH')
            <div class="col-lg-12">
                <div class="row">

                    <div class="tabs-container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true">Thể loại</a></li>
                            <li class=""><a data-toggle="tab" href="#tab-3" aria-expanded="false">SEO</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="name" class="col-sm-2 control-label">Thể loại:</label>
                                            <div class="col-sm-10">
                                                <input class="form-control" autocomplete="off" name="name" type="text" value="{{$news_category->name}}" id="name">
                                                <span class="text-danger">{{ $errors->first('name')}}</span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="slug" class="col-sm-2 control-label">Slug:</label>
                                            <div class="col-sm-10">
                                                <input class="form-control" autocomplete="off" name="slug" type="text" value="{{$news_category->slug}}" id="slug">
                                                <span class="text-danger">{{ $errors->first('slug')}}</span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="description" class="col-sm-2 control-label">Mô tả:</label>
                                            <div class="col-sm-10">
                                                <textarea class="form-control" name="description" cols="50" rows="10" id="description">{{$news_category->description}}</textarea>
                                                <span class="text-danger">{{ $errors->first('description')}}</span>
                                            </div>
                                        </div>

                                        <div class="hr-line-dashed"></div>

                                        <div class="form-group">
                                            <div class="col-sm-2"></div>
                                            <div class="col-sm-10">
                                                <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Cập nhật
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="tab-3" class="tab-pane">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="meta_title" class="col-sm-2 control-label">Meta title:</label>
                                            <div class="col-sm-10">
                                                <input class="form-control" autocomplete="off" name="meta_title" type="text" value="{{$news_category->meta_title}}" id="meta_title">
                                                <span class="text-danger">{{ $errors->first('meta_title')}}</span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="meta_description" class="col-sm-2 control-label">Meta description:</label>
                                            <div class="col-sm-10">
                                                <textarea class="form-control" rows="2" name="meta_description" cols="50" id="meta_description">{{$news_category->meta_description}}</textarea>
                                                <span class="text-danger">{{ $errors->first('meta_description')}}</span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="meta_keyword" class="col-sm-2 control-label">Meta keyword:</label>
                                            <div class="col-sm-10">
                                                <input class="form-control" autocomplete="off" name="meta_keyword" type="text" value="{{$news_category->meta_keyword}}" id="meta_keywords">
                                                <span class="text-danger">{{ $errors->first('meta_keyword')}}</span>
                                            </div>
                                        </div>

                                        <div class="hr-line-dashed"></div>

                                        <div class="form-group">
                                            <div class="col-sm-2"></div>
                                            <div class="col-sm-10">
                                                <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Cập nhật</button>
                                            </div>
                                        </div>
                                        <input type="hidden" name="news_category_id" value="{{$news_category->id}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection